version: '3.5'

services:
  # arjonas-api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   container_name: arjonas-api
  #   volumes:
  #     - .:/app
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL:-postgresql://root:123456@postgres:5432/postgres?schema=public}
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - network-app
  #   depends_on:
  #     - arjonas-postgres

  arjonas-postgres:
    container_name: arjonas-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - network-app
    restart: unless-stopped

networks:
  network-app:
    driver: bridge

volumes:
  postgres:
    driver: local
